# Generated by Django 5.0.6 on 2024-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='ZvxRsp7OqdLIYJv3cKCFZ91zjOAKDfKA8Tozoeluyu87UXxIKFAvJPWbqfYIxGt24D2RUznoU', max_length=73),
        ),
    ]
