# Generated by Django 5.0.6 on 2024-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='FlxbdxJ3CQ0DWZv2Ly864EYwuDIYBin5bxD2WZGOWnoKrvXMO9mA6P9tmaiXGd71uFJhiEv04', max_length=73),
        ),
    ]
