# Generated by Django 5.0.6 on 2024-07-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='iZkAVT1mG7trSbBnKGsjOy8usIXbpdl8UtPuTC52PLgy4RUSXtk7ttowywnvKDDCw18tlkQfd', max_length=73),
        ),
    ]
