# Generated by Django 5.0.6 on 2024-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='EvSJW3VeJUJnHNh3cYsoCNfsgNB6GnvOY5tBCc9FCJhllViofU57lVlz0VGioQQ51JqgMl5mv', max_length=73),
        ),
    ]
