# Generated by Django 5.0.6 on 2024-07-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='RKTbiqFqv2K9R0ygMPDNVFWwsmrSO1DOVUHHqcS97gBxqTEieY9XSU4DFHBInK0dwYry9dHy3', max_length=73, verbose_name='کد امنبتی '),
        ),
    ]
