# Generated by Django 5.0.6 on 2024-07-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_shopuser_first_name_alter_shopuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='ctdKiSERnaJA4salXkwIbTsOIT4usqa2NJUo0liCusiDfxX7GXLmyfbI6LNLAmHlrlem13Zi6', max_length=73, verbose_name='کد امنبتی '),
        ),
    ]
