# Generated by Django 5.0.6 on 2024-09-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='ZYrsV0puUMUilVos3fHNlcOox8u27VpbX5BON3OpM6nkZmfTL7VjN5DT1BahKIhZOf7nNIqGs', max_length=73, verbose_name='کد امنبتی '),
        ),
    ]
