# Generated by Django 5.0.6 on 2024-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='Y1HsKCHRgx2gdnyq3lASnMXn0tW1kXw0dAOqmTOnOPw5wRjXbt3D0uaRYZBKEcqxOi39RQ2Mn', max_length=73, verbose_name='کد امنبتی '),
        ),
    ]
