# Generated by Django 5.0.6 on 2024-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='EpkwWt3MzflGFxeab72wGnCpWRfGqjkNAEfS8vtKgjbc7f38FlGb8veEF1D1tXrY7XZQfkFhf', max_length=73, verbose_name='کد امنبتی '),
        ),
    ]
