# Generated by Django 5.0.6 on 2024-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_shopuser_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='secure_code',
            field=models.CharField(default='HWww8WZcLVY6rxbk6wsFrW8WwolT8qWM3g2v42mc14sSl0fdogJXTdqCNJJP2SIyqI8EvMxqE', max_length=73, verbose_name='کد امنبتی '),
        ),
    ]
