# Generated by Django 5.0.6 on 2024-09-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
