# Generated by Django 5.0.6 on 2024-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_cost_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه نهایی با تخفیف'),
        ),
    ]
